import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider"


import "./globals.css";



const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
      >
        <Sidebar>{children}</Sidebar>
      </ThemeProvider>

    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={dmSans.variable}>
        <head>
          <script
            async
            crossOrigin="anonymous"
            src="https://tweakcn.com/live-preview.min.js"
          />
        </head>
        <body className="font-sans antialiased">


          {children}

          <Toaster position="top-right" />

        </body>
      </html>
    </ClerkProvider>
  );
}
